#!/usr/bin/env bash

stty -echo
tput civis

trap 'stty echo; tput cnorm' EXIT

temp_file=$(mktemp)

printf '\e[8;38;108t\[\033[48;5;0;38;5;178m\]'

clear

cat << EOF
 ----------------------------------------------------  ----------------------------------------------------
|                                                    ||                                                    |
|                                                    ||                                                    |
|                                                    ||                                                    |
|                                                    ||                                                    |
|                                                    ||                                                    |
|                                                    ||                                                    |
|                                                    ||                                                    |
|                                                    ||                                                    |
|                                                    ||                                                    |
|                                                    ||                                                    |
|                                                    ||                                                    |
|                                                    ||                                                    |
|                                                    ||                                                    |
|                                                    ||                                                    |
|                                                    ||                                                    |
|                                                    ||                                                    |
|                                                    | ----------------------------------------------------
|                                                    |
|                                                    |
|                                                    |
|                                                    |
|                                                    |
|                                                    |
|                                                    |
|                                                    |
|                                                    |
|                                                    |
|                                                    |
|                                                    |
|                                                    |
|                                                    |
|                                                    |
|                                                    |
|                                                    |
 ----------------------------------------------------
EOF

print_cursors() {
    source $temp_file
    printf "\033[%s;%sH${cursor_status:0:1}" ${cursor_pos_lyrics[@]}
    printf '\033[17;'$cursor_pos_credits"H${cursor_status:1:1}"
}

cat >$temp_file << EOF
cursor_status=' _'
cursor_pos_lyrics=(2 3)
cursor_pos_credits=57
EOF
source $temp_file

while true; do
    sed -i "1s/'.*'/'${cursor_status:1:1}${cursor_status:0:1}'/" $temp_file
    print_cursors
    sleep .32
done &

print_ascii_art() {
    if [ $1 ]; then
        case $1 in
            'logo' ) print_ascii_art << 'EOF'
              .,-:;//;:=,
          . :H@@@MM@M#H/.,+%;,
       ,/X+ +M@@M@MM%=,-%HMMM@X/,
     -+@MM; $M@@MH+-,;XMMMM@MMMM@+-
    ;@M@@M- XM@X;. -+XXXXXHHH@M@M#@/.
  ,%MM@@MH ,@%=            .---=-=:=,.
  =@#@@@MX .,              -%HX$$%%%+;
 =-./@M@M$                  .;@MMMM@MM:
 X@/ -$MM/                    .+MM@@@M$
,@M@H: :@:                    . =X#@@@@-
,@@@MMX, .                    /H- ;@M@M=
.H@@@@M@+,                    %MM+..%#$.
 /MMMM@MMH/.                  XM@MH; =;
  /%+%$XHH@$=              , .H@@@@MX,
   .=--------.           -%H.,@@@@@MX,
   .%MM@@@HHHXX$$$%+- .:$MMX =M@@MM%.
     =XMMM@MM@MM#H;,-+HMM@M+ /MMMX=
       =%@M@M#@$-.=$@MM@@@M; %M%=
         ,:+$+-,/H#MMMMMMM@= =,
               =++%%%%+/:-.
EOF
            ;; 'explosion' ) print_ascii_art << 'EOF'
            .+
             /M;
              H#@:              ;,
              -###H-          -@/
               %####$.  -;  .%#X
                M#####+;#H :M#M.
..          .+/;%#########X###-
 -/%H%+;-,    +##############/
    .:$M###MH$%#############X  ,--=;-
        -/H#####################H+=.
            .+#################X.
          =%M####################H;.
             /@###############+;;/%%;,
          -%###################$.
        ;H######################M=
     ,%#####MH$%;+#####M###-/@####%
   :$H%+;=-      -####X.,H#   -+M##@-
  .              ,###;    ;      =$##+
                 .#H,               :XH,
                  +                   .;-
EOF
            ;; 'atom' ) print_ascii_art << 'EOF'
                 =/;;/-
                +:    //
               /;      /;
              -X        H.
.//;;;:;;-,   X=        :+   .-;:=;:;%;.
M-       ,=;;;#:,      ,:#;;:=,       ,@
:%           :%.=/++++/=.$=           %=
 ,%;         %/:+/;,,/++:+/         ;+.
   ,+/.    ,;@+,        ,%H;,    ,/+,
      ;+;;/= @.  .H##X   -X :///+;
      ;+=;;;.@,  .XM@$.  =X.//;=%/.
   ,;:      :@%=        =$H:     .+%-
 ,%=         %;-///==///-//         =%,
;+           :%-;;;:;;;;-X-           +:
@-      .-;;;;M-        =M/;;;-.      -X
 :;;::;;-.    %-        :+    ,-;;-;:==
              ,X        H.
               ;/      %=
                //    +;
                 ,////,
EOF
            ;; 'nuclear' ) print_ascii_art << 'EOF'
             =+$HM####@H%;,
          /H##############M$,
          ,@################+
           .H##############+
             X############/
              $##########/
               %########/
                /X/;;+X/

                 -XHHX-
                ,######,
#############X  .M####M.  X#############
##############-   -//-   -##############
X##############%,      ,+##############X
-##############X        X##############-
 %############%          %############%
  %##########;            ;##########%
   ;#######M=              =M#######;
    .+M###@,                ,@###M+.
       :XH.                  .HX:
EOF
            ;;
        esac
    else
        local line_no=19
        local IFS=''
        while read -r line; do
            printf "\033[$(( line_no++ ));61H%s\033[49D%s" \
                '                                                ' $line
        done
    fi
}

print_lyrics() {
    local processing_arg=false
    local new_line=true
    local args=(.088 0)
    local arg=
    for line in "${@}"; do
        if [ "$processing_arg" = true ]; then
            args[arg]=$line
            processing_arg=false
            continue
        elif [[ $line == -* ]]; then
            processing_arg=true
            case ${line:1:1} in
                r ) arg=0 ;;
                d ) arg=1 ;;
                n )
                    processing_arg=false
                    new_line=false
                ;; c)
                    processing_arg=false
                    sleep ${args[1]}
                    cursor_pos_lyrics=(2 3)
                    sed -i '2s/(.*)/(2 3)/' $temp_file
                    for i in {2..35}; do
                        printf "\033[$i;3H%s" \
                            '                                                 '
                    done
            esac
            continue
        fi

        sleep ${args[1]}

        local cursor_pos_start=${cursor_pos_lyrics[1]}
        for (( char=0; char<${#line}; char++ )); do
            (( cursor_pos_lyrics[1]++ ))
            sed -i "2s/[0-9]*)/${cursor_pos_lyrics[1]})/" $temp_file
            printf "\033[${cursor_pos_lyrics[0]};%sH${line:$char:1}" \
                $(( ${cursor_pos_lyrics[1]}-1 ))
            print_cursors
            sleep ${args[0]}
        done
        (( cursor_pos_lyrics[1]=cursor_pos_start+${#line} ))
        sed -i "2s/[0-9]*)/$(( cursor_pos_start+${#line} )))/" $temp_file
        printf "\033[${cursor_pos_lyrics[0]};"$cursor_pos_start"H$line"

        args[0]=.088

        if [ "$new_line" = true ]; then
            last_char=${cursor_pos_lyrics[@]}
            sed -i "2s/(.*)/($(( cursor_pos_lyrics[0]+1 )) 3)/" $temp_file
            printf '\033[%s;%sH ' ${last_char[@]}
            print_cursors
        else
            new_line=true
        fi
    done

    if [ "${@: -2:1}" = -d ]; then
        sleep ${args[1]}
    fi
}

sleep .1
print_lyrics -r .08 'Form FORM-29827281-12:' -r .08 'Test Assessment Report' \
    '' '' -d 2.9

aplay -q still_alive.wav &

print_lyrics 'This was a triumph.' -d .12

credits=('>LIST PERSONNEL' '' '' 'Gautam Babbar' 'Ted Backman' 'Kelly Bailey'
    'Jeff Ballinger' 'Aaron Barber' 'Jeep Barnett' 'Jeremy Bennett'
    'Dan Berger' 'Yahm Bernier' 'Ken Birdwell' 'Derrick Birum' 'Mike Blaszczak'
    'Iestyn Bleasdale-Shepherd' 'Chris Bokitch' 'Steve Bond' 'Matt Boone'
    'Antoine Bourdon' 'Jamaal Bradley' 'Jason Brashill' 'Charlie Brown'
    'Charlie Burgin' 'Andrew Burke' 'Augusta Butlin' 'Julie Caldwell'
    'Dario Casali' 'Chris Chin' 'Jess Cliffe' 'Phil Co' 'John Cook'
    'Christen Coomer' 'Greg Coomer' 'Scott Dalton' 'Kerry Davis'
    'Jason Deakins' 'Joe Demers' 'Ariel Diaz' 'Quintin Doroquez' 'Jim Dose'
    'Chris Douglass' 'Laura Dubuk' 'Mike Dunkle' 'Mike Durand' 'Mike Dussault'
    'Dhabih Eng' 'Katie Engel' 'Chet Faliszek' 'Adrian Finol' 'Bill Fletcher'
    'Moby Francke' 'Stephane Gaudette' 'Kathy Gehrig' 'Vitaliy Genkin'
    'Paul Graham' 'Chris Green' 'Chris Grinstead' 'John Guthrie'
    'Aaron Halifax' 'Reagan Halifax' 'Leslie Hall' 'Jeff Hameluck' 'Joe Han'
    'Don Holden' 'Jason Holtman' 'Gray Horsfield' 'Keith Huggins' 'Jim Hughes'
    'Jon Huisingh' 'Brian Jacobson' 'Lars Jensvold' 'Erik Johnson'
    'Jakob Jungels' 'Rich Kaethler' 'Steve Kalning' 'Aaron Kearly'
    'Iikka Keranen' 'David Kircher' 'Eric Kirchmer' 'Scott Klintworth'
    'Alden Kroll' 'Marc Laidlaw' 'Jeff Lane' 'Tim Larkin' 'Dan LeFree'
    'Isabelle LeMay' 'Tom Leonard' 'Jeff Lind' 'Doug Lombardi' 'Bianca Loomis'
    'Richard Lord' 'Realm Lovejoy' 'Randy Lundeen' 'Scott Lynch' 'Ido Magal'
    'Nick Maggiore' 'John McCaskey' 'Patrick McClard' 'Steve McClure'
    'Hamish McKenzie' 'Gary McTaggart' 'Jason Mitchell' 'Mike Morasky'
    'John Morello II' 'Bryn Moslow' 'Arsenio Navarro' 'Gabe Newell'
    'Milton Ngan' 'Jake Nicholson' 'Martin Otten' 'Nick Papineau' 'Karen Prell'
    'Bay Raitt' 'Tristan Reidford' 'Alfred Reynolds' 'Matt Rhoten'
    'Garret Rickey' 'Dave Riller' 'Elan Ruskin' 'Matthew Russell'
    'Jason Ruymen' 'David Sawyer' 'Marc Scaparro' 'Wade Schin' 'Matthew Scott'
    'Aaron Seeler' 'Jennifer Seeley' 'Taylor Sherman' 'Eric Smith'
    'Jeff Sorensen' 'David Speyrer' 'Jay Stelly' 'Jeremy Stone' 'Eric Strand'
    'Kim Swift' 'Kelly Thornton' 'Eric Twelker' 'Carl Uhlman' 'Doug Valente'
    'Bill Van Buren' 'Gabe Van Engel' 'Alex Vlachos' 'Robin Walker'
    'Joshua Weier' 'Andrea Wicklund' 'Greg Winkler' 'Erik Wolpaw' 'Doug Wood'
    'Matt T. Wood' 'Danika Wright' 'Matt Wright' 'Shawn Zabecki'
    'Torsten Zabka' '' '' '' '' "'Still Alive' 'by:" 'Jonathan Coulton' '' '' ''
    'Voices:' 'Ellen McLain - GlaDOS, Turrets' 'Mike Patton - THE ANGER SPHERE'
    '' '' '' 'Voice Casting:' 'Shana Landsburg\Teri Fiddleman' '' '' '' ''
    'Voice Recording:' 'Pure Audio, Seattle, WA' '' '' '' '' 'Voice recording'
    'scheduling and logistics:' 'Pat Cockburn, Pure Audio' '' '' '' ''
    'Translations:' 'SDL' '' '' '' '' 'Crack Legal Team:' 'Liam Lavery'
    'Karl Quackenbush' 'Kristen Boraas' 'Kevin Rosenfield' 'Alan Bruggeman'
    'Dennis Tessier' '' '' '' 'Thanks for the use of their face:'
    'Alesia Glidewell - Chell' '' '' '' 'Special thanks to everyone at:'
    'Alienware' 'ATI' 'Dell' 'Falcon Northwest' 'Havok' 'SOFTIMAGE'
    'and Don Kemmis, SLK Technologies' '' '' '' '' '' '' '' '' ''
    'THANK YOU FOR PARTICIPATING' 'IN THIS' 'ENRICHMENT CENTER ACTIVITY!!'
    '' '' '' '' '' ''
)
for ((  line_no=0; line_no<${#credits[@]}; line_no++ )); do
    line=${credits[$line_no]}
    for (( char=0; char<${#line}; char++ )); do
        (( cursor_pos_credits++ ))
        sed -i "3s/[0-9]*$/$cursor_pos_credits/" $temp_file
        printf "\033[17;$(( cursor_pos_credits-1 ))H${line:$char:1}"
        print_cursors
        sleep .066
    done
    sed -i "3s/[0-9]*$/57/" $temp_file
    for (( l=line_no; l>line_no-15 && l>=0; l-- )); do
        line=${credits[$l]}
        printf "\033[$(( 16+$l-$line_no ));57H$line%s$(printf ' %.0s' $(seq ${#line} 50))"
    done
    printf '\033[17;57H                                                 '
    print_cursors
done &

# -r rate -d delay -n no newline

print_lyrics -d 2 "I'm making a note here:" -d .1 -r .13 'HUGE SUCCESS.' \
    -d 1.2 -r 0.09 "It's hard to overstate" -d .3 -r .16 'my satisfaction.' \
    -d 2.2

print_ascii_art 'logo'

print_lyrics 'Aperture Science' -d 2.2 'We do what we must' -d .3 -n \
    'because ' -d .2 'we can.' -d 1.7 -r .12 'For the good of all of us' -d .3

print_ascii_art 'nuclear'

print_lyrics -r .058 'except the ones who are dead.' -d 0 '' -d .6

print_ascii_art 'logo'

print_lyrics -r 0.07 "But there's no sense crying" -d 0 'over every mistake.' \
    -d .2 'You just keep on trying' -d 0 -r .068 'till you run out of cake.' \
    -d .2 -r .075 'And the science gets done.' -d 0

print_ascii_art 'atom'

print_lyrics 'And you make a neat gun.'

print_ascii_art 'logo'

print_lyrics -r .066 'For the people who are' -d .1 'still alive.' -d 1.5 -c \
    -d .1 -r .028 'Forms FORM-55551-5:' -d 0 -r .045 \
    'Personnel File Addendum:' -d .7 '' -d 0 'Dear <<Subject Name Here>>,' '' \
    "I'm not even angry." -d 2.5 -n "I'm being " -d .2 -n -r .3 'so' -d 0 \
    ' sincere right now.' -d 1.7 -n -r .1 'Even though you '

print_ascii_art << 'EOF'
                          .,---.
                        ,/XM#MMMX;,
                      -%##########M%,
                     -@######%  $###@=
      .,--,         -H#######$   $###M:
   ,;$M###MMX;     .;##########$;HM###X=
 ,/@##########H=      ;################+
-+#############M/,      %##############+
%M###############=      /##############:
H################      .M#############;.
@###############M      ,@###########M:.
X################,      -$=X#######@:
/@##################%-     +######$-
.;##################X     .X#####+,
 .;H################/     -X####+.
   ,;X##############,       .MM/
      ,:+$H@M#######M#$-    .$$=
           .,-=;+$@###X:    ;/=.
                  .,/X$;   .::,
                      .,    ..
EOF

print_lyrics -r .1 'broke my heart.' -n 'And killed ' -d .2 -r .2 'me.' -d 1.8

print_ascii_art 'explosion'

print_lyrics -r .07 'And tore me to pieces.' -d 2.3 -n \
    'And threw every piece ' -d .1 -n -r .1 'into ' -d .1

print_ascii_art << 'EOF'
                     -\$-
                    .H##H,
                   +######+
                .+#########H.
              -$############@.
            =H###############@  -X:
          .$##################:  @#@-
     ,:  .M###################;  H###;
   ;@#:  @###################@  ,#####:
 -M###.  M#################@.  ;######H
 M####-  +###############$   =@#######X
 H####$   -M###########+   :#########M,
  /####X-   =########%   :M########@/.
    ,;%H@X;   .$###X   :##MM@%+;:-
                 ..
  -/;:-,.              ,,-==+M########H
 -##################@HX%%+%%$%%%+:,,
    .-/H%%%+%%$H@###############M@+=:/+:
/XHX%:#####MH%=    ,---:;;;;/%%XHM,:###$
$@#MX %+;-                           .
EOF

print_lyrics -r .15 'a fire.' -d 1.7 -r .095 'As they burned it hurt because' \
    -d .3

print_ascii_art << 'EOF'
                                     :X-
                                  :X###
                                ;@####@
                              ;M######X
                            -@########$
                          .$##########@
                         =M############-
                        +##############$
                      .H############$=.
         ,/:         ,M##########M;.
      -+@###;       =##########M;
   =%M#######;     :#########M/
-$M###########;   :#########/
 ,;X###########; =########$.
     ;H#########+#######M=
       ,+##############+
          /M#########@-
            ;M######%
              +####:
               ,$M-
EOF

print_lyrics -r .07 'I was so happy for you!' -d .4 'Now these points of data' \
    -d 0 'make a beautiful line.' "And we're out of beta." -r .08 \
    "We're releasing on time."

print_ascii_art 'explosion'

print_lyrics -r .08 "So I'm GLaD. I got burned."

print_ascii_art 'atom'

print_lyrics -r .058 'Think of all the things we learned'

print_ascii_art 'logo'

print_lyrics -r .07 'for the people who are' -r .15 'still alive.' -d 1.4 -c \
    -d .1 -r .02 'Forms FORM-55551-6:' -d 0 -r .04 \
    'Personnel File Addendum Addendum:' -d .5 '' -d 0 -r .14 \
    'One last thing:' '' -n 'Go ahead and leave ' -r .2 'me.' -d 1.5 -r .118 \
    'I think I prefer to stay inside.' -d 1.5 -r .112 \
    "Maybe you'll find someone else" -d 0 -r .1 'to help you.' -d 2.3 -n \
    'Maybe '

print_ascii_art << 'EOF'
           .-;+$XHHHHHHX$+;-.
        ,;X@@X%/;=----=:/%X@@X/
      =$@@%=.              .=+H@X:
    -XMX:                      =XMX=
   /@@:                          =H@+
  %@X,                            .$@$
 +@X.                               $@%
-@@,                                .@@=
%@%                                  +@$
H@:                                  :@H
H@:         :HHHHHHHHHHHHHHHHHHX,    =@H
%@%         ;@M@@@@@@@@@@@@@@@@@H-   +@$
=@@,        :@@@@@@@@@@@@@@@@@@@@@= .@@:
 +@X        :@@@@@@@@@@@@@@@M@@@@@@:%@%
  $@$,      ;@@@@@@@@@@@@@@@@@M@@@@@@$.
   +@@HHHHHHH@@@@@@@@@@@@@@@@@@@@@@@+
    =X@@@@@@@@@@@@@@@@@@@@@@@@@@@@X=
      :$@@@@@@@@@@@@@@@@@@@M@@@@$:
        ,;$@@@@@@@@@@@@@@@@@@X/-
            .-;+$XXHHHHHX$+;-.
EOF

print_lyrics -n 'Black ' -d 0 -n -r .3 'Mesa' -r .4 '...' -d .5 -n \
    'THAT WAS A JOKE.' -d 1 ' FAT CHANCE.' -d 1.56 -n -r .25 'Anywa'

print_ascii_art << 'EOF'
            ,:/+/-
            /M/              .,-=;//;-
       .:/= ;MH/,    ,=/+%$XH@MM#@:
      -$##@+$###@H@MMM#######H:.    -/H#
 .,H@H@ X######@ -H#####@+-     -+H###@X
  .,@##H;      +XM##M/,     =%@###@X;-
X%-  :M##########$.    .:%M###@%:
M##H,   +H@@@$/-.  ,;$M###@%,          -
M####M=,,---,.-%%H####M$:          ,+@##
@##################@/.         :%H##@$-
M###############H,         ;HM##M$=
#################.    .=$M##M$=
################H..;XM##M$=          .:+
M###################@%=           =+@MH%
@################M/.          =+H#X%=
=+M##############M,       -/X#X+;.
  .;XM##########H=    ,/X#H+:.
     ,:/%XM####H/.
          ,.:=-.

EOF

print_lyrics -r .08 'y, this cake is great.' -r .068 \
    "It's so delicious and moist." -d .5

print_ascii_art << 'EOF'
       #+ @      # #              M#@
 .    .X  X.%##@;# #   +@#######X. @#%
   ,==.   ,######M+  -#####%M####M-    #
  :H##M%:=##+ .M##M,;#####/+#######% ,M#
 .M########=  -@#@.=#####M=M#######=  X#
 :@@MMM##M.  -##M.,#######M#######. =  M
             @##..###:.    .H####, @@ X,
   ############: ###,/####;  /##= @#. M
           ,M## ;##,@#M;/M#M  @# X#% X#
.%=   ######M## ##.M#:   ./#M ,M #M ,#$
##/         $## #+;#: #### ;#/ M M- @# :
#+ #M@MM###M-;M #:$#-##$H# .#X @ + $#. #
      ######/.: #%=# M#:MM./#.-#  @#: H#
+,.=   @###: /@ %#,@  ##@X #,-#@.##% .@#
#####+;/##/ @##  #@,+       /#M    . X,
   ;###M#@ M###H .#M-     ,##M  ;@@; ###
   .M###%  ;####X ,@#######M/ -M###$  -H
    .M###%  X####H  .@@MM@;  ;@#M@
      H#M    /@####/      ,++.  / ==-,
               ,=/:, .+X@MMH@#H  #####$=
EOF

print_lyrics -d .1 -r .08 'Look at me still talking'

print_ascii_art 'nuclear'

print_lyrics -r .075 "when there's Science to do."

print_ascii_art 'logo'

print_lyrics -r .07 'When I look out there,' -r .07 \
    "It makes me GLaD I'm not you."

print_ascii_art 'atom'

print_lyrics "I've experiments to run."

print_ascii_art 'explosion'

print_lyrics -r .07 'There is research to be done.'

print_ascii_art 'logo'

print_lyrics -r .078 'On the people who are' -n 'still ' -r .24 'alive.' -c \
    '' '' '' 'PS: And believe me I am' 'still alive.' -d .8 -n -r .04 'PPS: ' \
    -d 0 -r .075 "I'm doing science and I'm" 'still alive.' -d .8 -n -r .04 \
    'PPPS: ' -d 0 -r .075 "I feel FANTASTIC and I'm" 'still alive.' '' \
    'FINAL THOUGHT:' -r .06 "While you're dying I'll be" 'still alive.' '' \
    -r .045 'FINAL THOUGHT PS:' -r .06 "And when you're dead I will be" \
    'still alive.' -d .45 '' 'STILL ALIVE' -d 0 -c

wait

