#!/usr/bin/env bash

stty -echo && tput civis # disable entering characters and hide the cursor
cleanup() {
    rm $cursor_file
    tput cnorm
    clear
}
trap cleanup EXIT

cursor_file=$(mktemp --tmpdir portal-XXX)
cat >$cursor_file << EOF
_ 
2 3
57
EOF
cursor_status='_ '
cursor_pos_lyrics_line=2
cursor_pos_lyrics_char=3
cursor_pos_credits=57

to_secs() { # convert nanoseconds to seconds
    local l=${#1}
    if (( $1 < 0 )); then # clamp negative values
        echo 0
    elif (( $l < 9 )); then # pad with zeros
        local zeros=000000000
        echo .${zeros:$l}$1
    else
        echo ${1:0:$l-9}.${1:$l-9}
    fi
}

update_cursors() {
    flock --no-fork $cursor_file sed --in-place "$1" $cursor_file
}

print_cursors() {
    # since parallel processes can't share variables
    # they have to be written and read into a file
    # cursor_status is a 2-character string, either
    # '_ ' or ' _'
    IFS='' read cursor_status # prevent ignoring whitespace
    read cursor_pos_lyrics_line cursor_pos_lyrics_char
    read cursor_pos_credits
    printf "\033[$cursor_pos_lyrics_line;$cursor_pos_lyrics_char""H${cursor_status:0:1}"
    printf '\033[17;'$cursor_pos_credits"H${cursor_status:1:1}"
} <$cursor_file

print_lyrics() {
    local new_line=true
    local rate=88
    local changing_rate=false
    for line in "${@}"; do
        if [ "$changing_rate" = true ]; then
            rate=$line
            changing_rate=false # so that the next argument doesn't get caught
            continue
        fi

        if [[ $line == -* ]]; then # if "option" , currently -c -n -r
            case ${line:1:1} in
                r ) # set a variable since the next argument will be the value
                changing_rate=true
             ;; n ) # set a variable to remember for the next line
                new_line=false
             ;; c ) # clear the screen
                cursor_pos_lyrics_line=2
                cursor_pos_lyrics_char=3
                update_cursors '2s/.*/2 3/'
                for i in {2..35}; do
                    printf "\033[$i;3H                                                 "
                done
             ;;
            esac
            continue
        fi

        if [[ $line =~ ^[0-9]+$ ]]; then
            # if the line is a number (not proceeded by -r)
            # then sleep until that time (in tenths of a second, i.e. 10=1s)
            # measured from the start of animation
            sleep $(to_secs $((100000000*$line+$start-$(date +%s%N))))
            continue
        fi

        local start_lyrics=$(date +%s%N)
        for (( char=0; char<${#line}; char++ )); do
            # update and record new cursor position
            (( cursor_pos_lyrics_char++ ))
            update_cursors "2s/[0-9]*$/$cursor_pos_lyrics_char/"

            # print character
            printf "\033[$cursor_pos_lyrics_line;$(( cursor_pos_lyrics_char-1 ))H${line:$char:1}"

            print_cursors # redraw the cursor on the next character

            sleep $(to_secs $((1000000*($char+1)*$rate+$start_lyrics-$(date +%s%N))))
        done

        rate=88 # change rate back to default

        if [ "$new_line" = true ]; then
            update_cursors "2s/.*/$(( cursor_pos_lyrics_line+1 )) 3/"

            # print a space over where the cursor used to be
            printf "\033[$cursor_pos_lyrics_line;$cursor_pos_lyrics_char"'H '

            print_cursors
        else
            new_line=true
        fi
    done
}

_print_ascii_art() {
    local line_no=19
    local IFS='' # so that whitespace in the heredoc is preserved
                 # this has the side effect that the spaces printed after
                 # the art (to cover up any previous residue) have to be
                 # explicitly typed (in other cases, an array is used)
    while read -r line; do
        printf "\033[$(( line_no++ ));61H                                         \033[41D%s" $line
    done
}

print_ascii_art() {
    case $1 in
        logo ) _print_ascii_art << 'EOF'
              .,-:;//;:=,
          . :H@@@MM@M#H/.,+%;,
       ,/X+ +M@@M@MM%=,-%HMMM@X/,
     -+@MM; $M@@MH+-,;XMMMM@MMMM@+-
    ;@M@@M- XM@X;. -+XXXXXHHH@M@M#@/.
  ,%MM@@MH ,@%=            .---=-=:=,.
  =@#@@@MX .,              -%HX$$%%%+;
 =-./@M@M$                  .;@MMMM@MM:
 X@/ -$MM/                    .+MM@@@M$
,@M@H: :@:                    . =X#@@@@-
,@@@MMX, .                    /H- ;@M@M=
.H@@@@M@+,                    %MM+..%#$.
 /MMMM@MMH/.                  XM@MH; =;
  /%+%$XHH@$=              , .H@@@@MX,
   .=--------.           -%H.,@@@@@MX,
   .%MM@@@HHHXX$$$%+- .:$MMX =M@@MM%.
     =XMMM@MM@MM#H;,-+HMM@M+ /MMMX=
       =%@M@M#@$-.=$@MM@@@M; %M%=
         ,:+$+-,/H#MMMMMMM@= =,
               =++%%%%+/:-.
EOF
     ;; explosion ) _print_ascii_art << 'EOF'
            .+
             /M;
              H#@:              ;,
              -###H-          -@/
               %####$.  -;  .%#X
                M#####+;#H :M#M.
..          .+/;%#########X###-
 -/%H%+;-,    +##############/
    .:$M###MH$%#############X  ,--=;-
        -/H#####################H+=.
            .+#################X.
          =%M####################H;.
             /@###############+;;/%%;,
          -%###################$.
        ;H######################M=
     ,%#####MH$%;+#####M###-/@####%
   :$H%+;=-      -####X.,H#   -+M##@-
  .              ,###;    ;      =$##+
                 .#H,               :XH,
                  +                   .;-
EOF
     ;; atom ) _print_ascii_art << 'EOF'
                 =/;;/-
                +:    //
               /;      /;
              -X        H.
.//;;;:;;-,   X=        :+   .-;:=;:;%;.
M-       ,=;;;#:,      ,:#;;:=,       ,@
:%           :%.=/++++/=.$=           %=
 ,%;         %/:+/;,,/++:+/         ;+.
   ,+/.    ,;@+,        ,%H;,    ,/+,
      ;+;;/= @.  .H##X   -X :///+;
      ;+=;;;.@,  .XM@$.  =X.//;=%/.
   ,;:      :@%=        =$H:     .+%-
 ,%=         %;-///==///-//         =%,
;+           :%-;;;:;;;;-X-           +:
@-      .-;;;;M-        =M/;;;-.      -X
 :;;::;;-.    %-        :+    ,-;;-;:==
              ,X        H.
               ;/      %=
                //    +;
                 ,////,
EOF
     ;; heart ) _print_ascii_art << 'EOF'
                          .,---.
                        ,/XM#MMMX;,
                      -%##########M%,
                     -@######%  $###@=
      .,--,         -H#######$   $###M:
   ,;$M###MMX;     .;##########$;HM###X=
 ,/@##########H=      ;################+
-+#############M/,      %##############+
%M###############=      /##############:
H################      .M#############;.
@###############M      ,@###########M:.
X################,      -$=X#######@:
/@##################%-     +######$-
.;##################X     .X#####+,
 .;H################/     -X####+.
   ,;X##############,       .MM/
      ,:+$H@M#######M#$-    .$$=
           .,-=;+$@###X:    ;/=.
                  .,/X$;   .::,
                      .,    ..
EOF
     ;; fire ) _print_ascii_art << 'EOF'
                     -\$-
                    .H##H,
                   +######+
                .+#########H.
              -$############@.
            =H###############@  -X:
          .$##################:  @#@-
     ,:  .M###################;  H###;
   ;@#:  @###################@  ,#####:
 -M###.  M#################@.  ;######H
 M####-  +###############$   =@#######X
 H####$   -M###########+   :#########M,
  /####X-   =########%   :M########@/.
    ,;%H@X;   .$###X   :##MM@%+;:-
                 ..
  -/;:-,.              ,,-==+M########H
 -##################@HX%%+%%$%%%+:,,
    .-/H%%%+%%$H@###############M@+=:/+:
/XHX%:#####MH%=    ,---:;;;;/%%XHM,:###$
$@#MX %+;-                           .
EOF
     ;; nuclear ) _print_ascii_art << 'EOF'
             =+$HM####@H%;,
          /H##############M$,
          ,@################+
           .H##############+
             X############/
              $##########/
               %########/
                /X/;;+X/

                 -XHHX-
                ,######,
#############X  .M####M.  X#############
##############-   -//-   -##############
X##############%,      ,+##############X
-##############X        X##############-
 %############%          %############%
  %##########;            ;##########%
   ;#######M=              =M#######;
    .+M###@,                ,@###M+.
       :XH.                  .HX:
EOF
     ;; tick ) _print_ascii_art << 'EOF'
                                     :X-
                                  :X###
                                ;@####@
                              ;M######X
                            -@########$
                          .$##########@
                         =M############-
                        +##############$
                      .H############$=.
         ,/:         ,M##########M;.
      -+@###;       =##########M;
   =%M#######;     :#########M/
-$M###########;   :#########/
 ,;X###########; =########$.
     ;H#########+#######M=
       ,+##############+
          /M#########@-
            ;M######%
              +####:
               ,$M-
EOF
     ;; mesa ) _print_ascii_art << 'EOF'
           .-;+$XHHHHHHX$+;-.
        ,;X@@X%/;=----=:/%X@@X/
      =$@@%=.              .=+H@X:
    -XMX:                      =XMX=
   /@@:                          =H@+
  %@X,                            .$@$
 +@X.                               $@%
-@@,                                .@@=
%@%                                  +@$
H@:                                  :@H
H@:         :HHHHHHHHHHHHHHHHHHX,    =@H
%@%         ;@M@@@@@@@@@@@@@@@@@H-   +@$
=@@,        :@@@@@@@@@@@@@@@@@@@@@= .@@:
 +@X        :@@@@@@@@@@@@@@@M@@@@@@:%@%
  $@$,      ;@@@@@@@@@@@@@@@@@M@@@@@@$.
   +@@HHHHHHH@@@@@@@@@@@@@@@@@@@@@@@+
    =X@@@@@@@@@@@@@@@@@@@@@@@@@@@@X=
      :$@@@@@@@@@@@@@@@@@@@M@@@@$:
        ,;$@@@@@@@@@@@@@@@@@@X/-
            .-;+$XXHHHHHX$+;-.
EOF
     ;; cake ) _print_ascii_art << 'EOF'
            ,:/+/-
            /M/              .,-=;//;-
       .:/= ;MH/,    ,=/+%$XH@MM#@:
      -$##@+$###@H@MMM#######H:.    -/H#
 .,H@H@ X######@ -H#####@+-     -+H###@X
  .,@##H;      +XM##M/,     =%@###@X;-
X%-  :M##########$.    .:%M###@%:
M##H,   +H@@@$/-.  ,;$M###@%,          -
M####M=,,---,.-%%H####M$:          ,+@##
@##################@/.         :%H##@$-
M###############H,         ;HM##M$=
#################.    .=$M##M$=
################H..;XM##M$=          .:+
M###################@%=           =+@MH%
@################M/.          =+H#X%=
=+M##############M,       -/X#X+;.
  .;XM##########H=    ,/X#H+:.
     ,:/%XM####H/.
          ,.:=-.

EOF
     ;; glados ) _print_ascii_art << 'EOF'
       #+ @      # #              M#@
 .    .X  X.%##@;# #   +@#######X. @#%
   ,==.   ,######M+  -#####%M####M-    #
  :H##M%:=##+ .M##M,;#####/+#######% ,M#
 .M########=  -@#@.=#####M=M#######=  X#
 :@@MMM##M.  -##M.,#######M#######. =  M
             @##..###:.    .H####, @@ X,
   ############: ###,/####;  /##= @#. M
           ,M## ;##,@#M;/M#M  @# X#% X#
.%=   ######M## ##.M#:   ./#M ,M #M ,#$
##/         $## #+;#: #### ;#/ M M- @# :
#+ #M@MM###M-;M #:$#-##$H# .#X @ + $#. #
      ######/.: #%=# M#:MM./#.-#  @#: H#
+,.=   @###: /@ %#,@  ##@X #,-#@.##% .@#
#####+;/##/ @##  #@,+       /#M    . X,
   ;###M#@ M###H .#M-     ,##M  ;@@; ###
   .M###%  ;####X ,@#######M/ -M###$  -H
    .M###%  X####H  .@@MM@;  ;@#M@
      H#M    /@####/      ,++.  / ==-,
               ,=/:, .+X@MMH@#H  #####$=
EOF
     ;;
    esac
}

printf '\033[8;38;108t\[\033[48;5;0;38;5;178m\]' # set dimensions, then colours
clear
printf ' ---------------------------------------------------- %.0s' 1 2
printf '\n'
printf "$(printf '|                                                    |%.0s' 1 2)\n%.0s" {1..16}
printf '|                                                    | ----------------------------------------------------\n'
printf '|                                                    |\n%.0s' {1..17}
printf ' ----------------------------------------------------'

while true; do # blink cursors
    update_cursors "1s/.*/${cursor_status:1:1}${cursor_status:0:1}/"
    print_cursors
    sleep .3
done &

start=$(date +%s%N)
print_lyrics 1 -r 80 'Form FORM-29827281-12:' -r 80 'Test Assessment Report' \
    '' '' 70

dir=$(dirname $0)
aplay -q $dir/still_alive.wav &

print_lyrics 'This was a triumph.' 91

credits=(
    '>LIST PERSONNEL' '' '' 'Gautam Babbar' 'Ted Backman' 'Kelly Bailey'
    'Jeff Ballinger' 'Aaron Barber' 'Jeep Barnett' 'Jeremy Bennett'
    'Dan Berger' 'Yahm Bernier' 'Ken Birdwell' 'Derrick Birum' 'Mike Blaszczak'
    'Iestyn Bleasdale-Shepherd' 'Chris Bokitch' 'Steve Bond' 'Matt Boone'
    'Antoine Bourdon' 'Jamaal Bradley' 'Jason Brashill' 'Charlie Brown'
    'Charlie Burgin' 'Andrew Burke' 'Augusta Butlin' 'Julie Caldwell'
    'Dario Casali' 'Chris Chin' 'Jess Cliffe' 'Phil Co' 'John Cook'
    'Christen Coomer' 'Greg Coomer' 'Scott Dalton' 'Kerry Davis' 'Jason Deakins'
    'Joe Demers' 'Ariel Diaz' 'Quintin Doroquez' 'Jim Dose' 'Chris Douglass'
    'Laura Dubuk' 'Mike Dunkle' 'Mike Durand' 'Mike Dussault' 'Dhabih Eng'
    'Katie Engel' 'Chet Faliszek' 'Adrian Finol' 'Bill Fletcher' 'Moby Francke'
    'Stephane Gaudette' 'Kathy Gehrig' 'Vitaliy Genkin' 'Paul Graham'
    'Chris Green' 'Chris Grinstead' 'John Guthrie' 'Aaron Halifax'
    'Reagan Halifax' 'Leslie Hall' 'Jeff Hameluck' 'Joe Han' 'Don Holden'
    'Jason Holtman' 'Gray Horsfield' 'Keith Huggins' 'Jim Hughes' 'Jon Huisingh'
    'Brian Jacobson' 'Lars Jensvold' 'Erik Johnson' 'Jakob Jungels'
    'Rich Kaethler' 'Steve Kalning' 'Aaron Kearly' 'Iikka Keranen'
    'David Kircher' 'Eric Kirchmer' 'Scott Klintworth' 'Alden Kroll'
    'Marc Laidlaw' 'Jeff Lane' 'Tim Larkin' 'Dan LeFree' 'Isabelle LeMay'
    'Tom Leonard' 'Jeff Lind' 'Doug Lombardi' 'Bianca Loomis' 'Richard Lord'
    'Realm Lovejoy' 'Randy Lundeen' 'Scott Lynch' 'Ido Magal' 'Nick Maggiore'
    'John McCaskey' 'Patrick McClard' 'Steve McClure' 'Hamish McKenzie'
    'Gary McTaggart' 'Jason Mitchell' 'Mike Morasky' 'John Morello II'
    'Bryn Moslow' 'Arsenio Navarro' 'Gabe Newell' 'Milton Ngan' 'Jake Nicholson'
    'Martin Otten' 'Nick Papineau' 'Karen Prell' 'Bay Raitt' 'Tristan Reidford'
    'Alfred Reynolds' 'Matt Rhoten' 'Garret Rickey' 'Dave Riller' 'Elan Ruskin'
    'Matthew Russell' 'Jason Ruymen' 'David Sawyer' 'Marc Scaparro' 'Wade Schin'
    'Matthew Scott' 'Aaron Seeler' 'Jennifer Seeley' 'Taylor Sherman'
    'Eric Smith' 'Jeff Sorensen' 'David Speyrer' 'Jay Stelly' 'Jeremy Stone'
    'Eric Strand' 'Kim Swift' 'Kelly Thornton' 'Eric Twelker' 'Carl Uhlman'
    'Doug Valente' 'Bill Van Buren' 'Gabe Van Engel' 'Alex Vlachos'
    'Robin Walker' 'Joshua Weier' 'Andrea Wicklund' 'Greg Winkler' 'Erik Wolpaw'
    'Doug Wood' 'Matt T. Wood' 'Danika Wright' 'Matt Wright' 'Shawn Zabecki'
    'Torsten Zabka' '' '' '' '' "'Still Alive' by:" 'Jonathan Coulton' '' '' ''
    'Voices:' 'Ellen McLain - GlaDOS, Turrets' 'Mike Patton - THE ANGER SPHERE'
    '' '' '' 'Voice Casting:' 'Shana Landsburg\Teri Fiddleman' '' '' '' ''
    'Voice Recording:' 'Pure Audio, Seattle, WA' '' '' '' '' 'Voice recording'
    'scheduling and logistics:' 'Pat Cockburn, Pure Audio' '' '' '' ''
    'Translations:' 'SDL' '' '' '' '' 'Crack Legal Team:' 'Liam Lavery'
    'Karl Quackenbush' 'Kristen Boraas' 'Kevin Rosenfield' 'Alan Bruggeman'
    'Dennis Tessier' '' '' '' 'Thanks for the use of their face:'
    'Alesia Glidewell - Chell' '' '' '' 'Special thanks to everyone at:'
    'Alienware' 'ATI' 'Dell' 'Falcon Northwest' 'Havok' 'SOFTIMAGE'
    'and Don Kemmis, SLK Technologies' '' '' '' '' '' '' '' '' ''
    'THANK YOU FOR PARTICIPATING' 'IN THIS' 'ENRICHMENT CENTER ACTIVITY!!' ''
    '' '' '' '' ''
)
chars=1
for ((  line_no=0; line_no<${#credits[@]}; line_no++ )); do
    line=${credits[$line_no]}
    for (( char=0; char<${#line}; char++, chars++ )); do
        (( cursor_pos_credits++ ))
        update_cursors "3s/.*/$cursor_pos_credits/"

        printf "\033[17;$(( cursor_pos_credits-1 ))H${line:$char:1}"

        print_cursors

        sleep 2>/dev/null $(to_secs $((9100000000+70000000*$chars+$start-$(date +%s%N))))
    done

    update_cursors "3s/.*/57/"

    # move the lines up
    for (( l=line_no; l>line_no-15 && l>=0; l-- )); do
        line=${credits[$l]}
        printf "\033[$(( 16+$l-$line_no ));57H$line$(printf ' %.0s' $(seq ${#line} 50))"
    done

    printf '\033[17;57H                                                 '
    print_cursors
done &

# -c clear
# -n no newline
# -r rate

print_lyrics 109 "I'm making a note here:" 132 -r 130 'HUGE SUCCESS.' 159 \
    -r 90 "It's hard to overstate" 184 -r 160 'my satisfaction.' 232

print_ascii_art logo

print_lyrics 'Aperture Science' 270 'We do what we must' 288 -n 'because ' 297 \
    'we can.' 321 -r 120 'For the good of all of us' 353

print_ascii_art nuclear

print_lyrics -r 58 'except the ones who are dead.' '' 375

print_ascii_art logo

print_lyrics -r 70 "But there's no sense crying" 'over every mistake.' 414 \
    'You just keep on trying' -r 68 'till you run out of cake.' 453 -r 75 \
    'And the science gets done.'

print_ascii_art atom

print_lyrics 'And you make a neat gun.'

print_ascii_art logo

print_lyrics -r 65 'For the people who are' 509 'still alive.' 538 -c 539 \
    -r 28 'Forms FORM-55551-5:' -r 45 'Personnel File Addendum:' 562 '' \
    'Dear <<Subject Name Here>>,' '' "I'm not even angry." 629 -n "I'm being " \
    639 -n -r 300 'so' ' sincere right now.' 680 -n -r 100 'Even though you '

print_ascii_art heart

print_lyrics -r 100 'broke my heart.' -n 'And killed ' 723 -r 200 'me.' 748

print_ascii_art explosion

print_lyrics -r 70 'And tore me to pieces.' 787 -n 'And threw every piece ' 806 -n -r 100 'into ' 815

print_ascii_art fire

print_lyrics -r 150 'a fire.' 840 -r 95 'As they burned it hurt because' 872

print_ascii_art tick

print_lyrics -r 70 'I was so happy for you!' 893 'Now these points of data' \
    'make a beautiful line.' "And we're out of beta." -r 80 \
    "We're releasing on time."

print_ascii_art explosion

print_lyrics -r 80 "So I'm GLaD. I got burned."

print_ascii_art atom

print_lyrics -r 58 'Think of all the things we learned'

print_ascii_art logo

print_lyrics -r 70 'for the people who are' -r 150 'still alive.' 1062 -c \
    1063 -r 20 'Forms FORM-55551-6:' -r 40 'Personnel File Addendum Addendum:' \
    1089 '' -r 140 'One last thing:' '' -n 'Go ahead and leave ' -r 200 'me.' \
    1148 -r 118 'I think I prefer to stay inside.' 1202 -r 112 \
    "Maybe you'll find someone else" -r 100 'to help you.' 1271 -n 'Maybe '

print_ascii_art mesa

print_lyrics -n 'Black ' -n -r 300 'Mesa' -r 400 '...' 1311 -n \
    'THAT WAS A JOKE.' 1335 ' FAT CHANCE.' 1363 -n -r 250 'Anywa'

print_ascii_art cake

print_lyrics -r 80 'y, this cake is great.' -r 68 "It's so delicious and moist." 1416

print_ascii_art glados

print_lyrics 1416 -r 80 'Look at me still talking'

print_ascii_art nuclear

print_lyrics -r 75 "when there's Science to do."

print_ascii_art logo

print_lyrics -r 70 'When I look out there,' -r 70 "It makes me GLaD I'm not you."

print_ascii_art atom

print_lyrics "I've experiments to run."

print_ascii_art explosion

print_lyrics -r 70 'There is research to be done.'

print_ascii_art logo

print_lyrics -r 78 'On the people who are' -n 'still ' -r 240 'alive.' -c \
    '' '' '' 'PS: And believe me I am' 'still alive.' 1612 -n -r 40 'PPS: ' \
    -r 75 "I'm doing science and I'm" 'still alive.' 1652 -n -r 40 'PPPS: ' \
    -r 75 "I feel FANTASTIC and I'm" 'still alive.' '' 'FINAL THOUGHT:' -r 60 \
    "While you're dying I'll be" 'still alive.' '' -r 45 'FINAL THOUGHT PS:' \
    -r 60 "And when you're dead I will be" 'still alive.' 1768 '' 1773 \
    'STILL ALIVE' -c

wait
